export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
export const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";
export const REDUCE_PRODUCT_QUANTITY = "REDUCE_PRODUCT_QUANTITY";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const PROCEED_TO_CHECKOUT = "PROCEED_TO_CHECKOUT";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS ";
export const CHECKOUT_FAILED = "CHECKOUT_FAILED";
